"""Signalroom backend foundation package."""

from .config import Settings, get_settings
from .models import (
    ArticleActionCreate,
    ArticleActionRead,
    ArticleActionRequest,
    ArticleActionType,
    ArticleCreate,
    ArticleRead,
    ArticleSourceCreate,
    ArticleSourceRead,
    BriefingSnapshotCreate,
    BriefingSnapshotRead,
    Capability,
    ClusterCreate,
    ClusterRead,
    CrawlJobCreate,
    CrawlJobEventCreate,
    CrawlJobEventRead,
    CrawlJobRead,
    CrawlJobStatus,
    CrawlJobUpdate,
    Page,
    PageParams,
    ProfileId,
    TelemetryEventCreate,
    TelemetryEventRead,
    VocFeedbackCreate,
    VocFeedbackRead,
    make_stable_id,
)
from .profiles import LoadedProfile, ProfileRegistry, load_profile, load_profiles
from .security import Principal, hash_client_ip, resolve_client_ip, resolve_principal
from .json_storage import JSONRepository, Repository
from .storage import SQLiteRepository

__all__ = [
    "ArticleActionCreate",
    "ArticleActionRead",
    "ArticleActionRequest",
    "ArticleActionType",
    "ArticleCreate",
    "ArticleRead",
    "ArticleSourceCreate",
    "ArticleSourceRead",
    "BriefingSnapshotCreate",
    "BriefingSnapshotRead",
    "Capability",
    "ClusterCreate",
    "ClusterRead",
    "CrawlJobCreate",
    "CrawlJobEventCreate",
    "CrawlJobEventRead",
    "CrawlJobRead",
    "CrawlJobStatus",
    "CrawlJobUpdate",
    "LoadedProfile",
    "JSONRepository",
    "Page",
    "PageParams",
    "Principal",
    "ProfileId",
    "ProfileRegistry",
    "Repository",
    "SQLiteRepository",
    "Settings",
    "TelemetryEventCreate",
    "TelemetryEventRead",
    "VocFeedbackCreate",
    "VocFeedbackRead",
    "get_settings",
    "hash_client_ip",
    "load_profile",
    "load_profiles",
    "make_stable_id",
    "resolve_client_ip",
    "resolve_principal",
]

__version__ = "0.1.0"
