"use client";

import { useState, type ReactNode } from "react";
import type { Article, BriefingHistoryRecord, ColorTheme, DetailedAnalytics, GatekeeperAudit, SourceRecord, ViewerProfile, WorkflowItem } from "@/types/news";
import type { VocResponse } from "@/lib/signalroom-client";
import { ArticleSelectionToggle, EmptyState, Icon, PriorityBadge, SafeImage, ScoreRing, SourceBadge, StatusBadge } from "@/components/ui";

function PageIntro({ eyebrow, title, copy, actions }: { eyebrow: string; title: string; copy: string; actions?: ReactNode }) {
  return <div className="page-masthead"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{copy}</p></div>{actions && <div className="masthead-actions">{actions}</div>}</div>;
}

export function WorkflowView({ items, onMove, onExport, onOpen }: { items: WorkflowItem[]; onMove: (articleId: string, status: string) => Promise<void>; onExport: () => void; onOpen: (articleId: string) => void }) {
  const [view, setView] = useState<"kanban" | "table" | "list">("kanban");
  const [dragged, setDragged] = useState<string | null>(null);
  const [moving, setMoving] = useState<string | null>(null);
  const columns = ["New", "Under Review", "Selected", "Approved"];
  const move = async (status: string) => { if (!dragged || moving) return; const item = items.find((entry) => entry.id === dragged); setDragged(null); if (!item || item.status === status) return; setMoving(item.id); try { await onMove(item.articleId, status); } finally { setMoving(null); } };
  return <div className="page-content workflow-page">
    <PageIntro eyebrow="Editorial decision pipeline" title="Workflow" copy="Backend worklists for review, selection, approval, and export." actions={<button className="primary-button" onClick={onExport} disabled={!items.length}><Icon>↥</Icon>Export worklist</button>} />
    <div className="workflow-toolbar"><div className="view-tabs" role="group" aria-label="Workflow view">{(["kanban", "table", "list"] as const).map((item) => <button className={view === item ? "active" : ""} key={item} onClick={() => setView(item)}>{item}</button>)}</div><div className="workflow-summary"><span>{items.length} active items</span></div></div>
    {!items.length ? <EmptyState title="Workflow is empty" copy="Move an article under review to add it here." /> : view === "kanban" ? <div className="kanban-board" aria-busy={Boolean(moving)}>{columns.map((column) => <section className={`kanban-column column-${column.toLowerCase().replaceAll(" ", "-")}`} key={column} onDragOver={(event) => event.preventDefault()} onDrop={() => void move(column)}><header><div><i /><strong>{column}</strong></div><span>{items.filter((item) => item.status === column).length}</span></header><div className="kanban-items">{items.filter((item) => item.status === column).map((item) => <article className={`workflow-card priority-${item.priority}`} key={item.id} draggable={!moving} onDragStart={() => setDragged(item.id)}><div className="workflow-card-top"><PriorityBadge priority={item.priority} />{moving === item.id && <StatusBadge tone="live">Saving…</StatusBadge>}</div><button className="workflow-title" onClick={() => onOpen(item.articleId)}>{item.title}</button><div className="workflow-tags"><span>{item.category}</span><span>{item.team}</span></div><div className="owner-row"><span className="mini-avatar">{item.owner.split(/\s+/).map((part) => part[0]).slice(0, 2).join("")}</span><span>{item.owner}</span></div></article>)}</div></section>)}</div> : <div className="data-table workflow-table"><div className="table-head"><span>Story</span><span>Owner</span><span>Priority</span><span>Status</span><span>Created</span><span>Sources</span></div>{items.map((item) => <div className="table-row" key={item.id}><button onClick={() => onOpen(item.articleId)}>{item.title}</button><span>{item.owner}</span><PriorityBadge priority={item.priority} /><StatusBadge tone="review">{item.status}</StatusBadge><span>{item.created}</span><span>{item.attachments}</span></div>)}</div>}
  </div>;
}

export function SavedView({ articles, saved, selectedIds, onToggleSelected, onSave, onWorkflow, onOpen, onExport }: { articles: Article[]; saved: Set<string>; selectedIds: Set<string>; onToggleSelected: (id: string) => void; onSave: (id: string) => void; onWorkflow: (article: Article) => void; onOpen: (article: Article) => void; onExport: () => void }) {
  const rows = articles.filter((article) => saved.has(article.id));
  return <div className="page-content saved-page"><PageIntro eyebrow="Your research library" title="Saved" copy="Saved records are retained by the backend beyond the rolling briefing history." actions={<button className="primary-button" onClick={onExport} disabled={!rows.length}><Icon>↥</Icon>Export saved</button>} />
    {!rows.length ? <EmptyState title="Nothing saved yet" copy="Save a signal from the briefing to build your library." /> : <div className="saved-grid">{rows.map((article) => <article className={selectedIds.has(article.id) ? "is-selected" : ""} key={article.id}>
      <div className="saved-selection"><ArticleSelectionToggle checked={selectedIds.has(article.id)} label={article.headline} onChange={() => onToggleSelected(article.id)} compact /></div>
      <SafeImage src={article.image} alt="" />
      <div className="saved-card-body"><div><SourceBadge code={article.sourceCode} name={article.source} /><span>{article.source} · {article.published}</span><PriorityBadge priority={article.priority} /></div><button onClick={() => onOpen(article)}><h3>{article.headline}</h3></button><p>{article.summary}</p><div className="saved-actions"><button className="secondary-button" onClick={() => onOpen(article)}>Open dossier</button><button className="secondary-button" onClick={() => onWorkflow(article)}>Under review</button><button className="icon-button" onClick={() => onSave(article.id)} aria-label="Remove from saved"><Icon>◆</Icon></button></div></div>
    </article>)}</div>}
  </div>;
}

export function SelectedView({ articles, selectedIds, statusById, saved, onToggleSelected, onStatus, onSave, onOpen, onExport }: { articles: Article[]; selectedIds: Set<string>; statusById: Record<string, string>; saved: Set<string>; onToggleSelected: (id: string) => void; onStatus: (id: string, status: string) => void; onSave: (id: string) => void; onOpen: (article: Article) => void; onExport: () => void }) {
  const rows = articles.filter((article) => selectedIds.has(article.id));
  return <div className="page-content selected-page"><PageIntro eyebrow="Decision-ready intelligence" title="Selected" copy="Your backend-persisted export set follows you across screens." actions={<button className="primary-button" onClick={onExport} disabled={!rows.length}><Icon>↥</Icon>Export {rows.length} selected</button>} />
    {!rows.length ? <EmptyState icon="✓" title="Your selected set is empty" copy="Select any article to add it here." /> : <div className="selected-list">{rows.map((article) => <article className="is-selected" key={article.id}>
      <ArticleSelectionToggle checked label={article.headline} onChange={() => onToggleSelected(article.id)} compact /><SafeImage src={article.image} alt="" />
      <div><span className="source-line"><SourceBadge code={article.sourceCode} name={article.source} /><b>{article.source}</b><span>{article.published}</span><StatusBadge tone="ai">{statusById[article.id] ?? article.status}</StatusBadge></span><button className="selected-title" onClick={() => onOpen(article)}>{article.headline}</button><p>{article.summary}</p><span className="selected-tags">{article.region} · {article.keywords.slice(0, 3).join(" · ")}</span></div><div className="selected-actions"><button className="secondary-button" onClick={() => onStatus(article.id, "Under Review")}>Under review</button><button className={`secondary-button ${saved.has(article.id) ? "active" : ""}`} onClick={() => onSave(article.id)}>{saved.has(article.id) ? "Saved" : "Save"}</button><button className="primary-button" onClick={() => onOpen(article)}>Open dossier</button></div>
    </article>)}</div>}
  </div>;
}

export function GatekeeperView({ audit, onDropped }: { audit: GatekeeperAudit | null; onDropped: () => void }) {
  const counts = audit?.counters.articles;
  const total = counts?.total ?? 0;
  const retention = total ? Math.round(((counts?.retained ?? 0) / total) * 1000) / 10 : 0;
  return <div className="page-content gatekeeper-page"><PageIntro eyebrow="AI relevance audit" title="Gatekeeper" copy="The latest persisted run, including retained, review, and dropped decisions." actions={<button className="secondary-button" onClick={onDropped}>Review dropped articles <Icon>→</Icon></button>} />
    {!audit?.job ? <EmptyState title="No Gatekeeper run available" copy="Complete a source scan to populate the audit." /> : <><section className="gatekeeper-hero"><div><span className="ai-label">✦ LATEST SUCCESSFUL RUN</span><h2>{retention}% of evaluated articles were retained.</h2><p>Job {audit.job.id} · {new Date(audit.job.completed_at ?? audit.job.created_at).toLocaleString()}</p><div className="gatekeeper-stats"><div><strong>{total}</strong><span>Evaluated</span></div><div><strong>{counts?.retained ?? 0}</strong><span>Retained</span></div><div><strong>{counts?.review ?? 0}</strong><span>Review</span></div><div><strong>{counts?.dropped ?? 0}</strong><span>Dropped</span></div></div></div></section><section className="panel anomaly-panel"><div className="panel-title"><div><span className="eyebrow">Requires judgment</span><h3>Review bucket</h3></div><span>{counts?.review ?? 0} candidates</span></div><div className="dropped-list">{audit.articles.filter((item) => item.gatekeeper.bucket === "review").slice(0, 8).map((item) => <article key={item.article_id}><ScoreRing value={Math.round((item.gatekeeper.score ?? 0) * 100)} /><div><h3>{item.title}</h3><p>{item.gatekeeper.reason}</p></div></article>)}</div></section></>}
  </div>;
}

export function DroppedView({ audit, onRestore, onHide, onWorkflow }: { audit: GatekeeperAudit | null; onRestore: (id: string) => void; onHide: (id: string) => void; onWorkflow: (id: string) => void }) {
  const rows = audit?.articles.filter((item) => item.gatekeeper.bucket === "dropped" && !item.disposition?.hidden && !item.disposition?.under_review && !item.disposition?.selected && !item.disposition?.approved) ?? [];
  return <div className="page-content dropped-page"><PageIntro eyebrow="Gatekeeper rejection log" title="Dropped Articles" copy="Audit the dropped bucket from the latest successful profile run." />
    {!rows.length ? <EmptyState title="No dropped articles" copy="There is no current dropped queue for this profile." /> : <div className="dropped-list">{rows.map((item) => <article key={item.article_id}><span className="rejection-rail" /><div className="drop-score"><ScoreRing value={Math.round((item.gatekeeper.score ?? 0) * 100)} /><span>relevance</span></div><div className="drop-copy"><div><StatusBadge tone="rejected">Dropped</StatusBadge><span>{item.source ?? "Unknown source"}</span></div><h3>{item.title}</h3><div className="rejection-reason"><span>GATEKEEPER REASON</span><p>{item.gatekeeper.reason}</p></div></div><div className="drop-actions"><button className="primary-button" onClick={() => onRestore(item.article_id)}><Icon>↺</Icon>Restore</button><button className="secondary-button" onClick={() => onWorkflow(item.article_id)}>Add to workflow</button><button className="ghost-button" onClick={() => onHide(item.article_id)}>Hide</button></div></article>)}</div>}
  </div>;
}

export function NotInterestedView({ articles, onRestore, onRemove, viewerName }: { articles: Article[]; onRestore: (id: string) => void; onRemove: (id: string) => void; viewerName: string }) {
  return <div className="page-content not-interested-page"><PageIntro eyebrow="Preference feedback" title="Not Interested" copy="Stories you dismissed for this profile and identity." />
    {!articles.length ? <EmptyState title="No dismissed stories" copy="Articles marked Not Interested will appear here." /> : <div className="not-list">{articles.map((article) => <article key={article.id}><div className="not-icon"><Icon>⊘</Icon></div><div><span className="eyebrow">{article.category} · {article.source}</span><h3>{article.headline}</h3><p>Marked not interested by {viewerName}.</p></div><div className="not-actions"><button className="primary-button" onClick={() => onRestore(article.id)}><Icon>↺</Icon>Restore</button><button className="ghost-button" onClick={() => onRemove(article.id)}>Hide</button></div></article>)}</div>}
  </div>;
}

export function HistoryView({ items, onOpen, hasMore, loadingMore, onLoadMore }: { items: BriefingHistoryRecord[]; onOpen: (item: BriefingHistoryRecord) => void; hasMore: boolean; loadingMore: boolean; onLoadMore: () => void }) {
  return <div className="page-content history-page">
    <PageIntro eyebrow="Rolling 30-day briefing archive" title="History" copy="Immutable backend snapshots. Saved articles remain in Saved even after a briefing leaves this archive." />
    {!items.length ? <EmptyState title="No briefing history" copy="Completed retained scans create history snapshots." /> : <div className="history-list">{items.map((item) => <article key={item.id}>
      <time><strong>{new Date(item.created_at).toLocaleDateString([], { day: "2-digit", month: "short" })}</strong><span>{new Date(item.created_at).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</span></time>
      <div><span className="eyebrow">{item.profile} profile</span><h3>{item.articles[0]?.title ?? `${item.article_ids.length} article briefing`}</h3><p>{item.article_ids.length} retained articles · Job {item.crawl_job_id ?? "not recorded"}</p></div>
      <button className="secondary-button" onClick={() => onOpen(item)}>Open complete snapshot <Icon>→</Icon></button>
    </article>)}</div>}
    {hasMore && <div className="history-pagination"><button className="secondary-button" disabled={loadingMore} onClick={onLoadMore}>{loadingMore ? "Loading…" : "Load older snapshots"} <Icon>↓</Icon></button></div>}
  </div>;
}
export function SourcesView({ sources, readOnly, onAdd, onEdit }: { sources: SourceRecord[]; readOnly: boolean; onAdd: () => void; onEdit: (source: SourceRecord) => void }) {
  const [query, setQuery] = useState("");
  const rows = sources.filter((source) => source.name.toLowerCase().includes(query.toLowerCase()));
  return <div className="page-content sources-page"><PageIntro eyebrow="Collection infrastructure" title="Sources" copy="Profile-scoped crawler configuration loaded from the backend." actions={!readOnly ? <button className="primary-button" onClick={onAdd}><Icon>＋</Icon>Add source</button> : undefined} />
    <div className="source-health-ribbon"><div><span className="pulse-dot" /><span><strong>{sources.filter((source) => source.enabled).length} active</strong><small>of {sources.length} configured</small></span></div><div><strong>{sources.filter((source) => source.deepScan).length}</strong><span>Deep scan</span></div><div><strong>{sources.filter((source) => source.rssUrl).length}</strong><span>RSS feeds</span></div></div>
    <div className="source-toolbar"><label><Icon>⌕</Icon><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search sources" /></label><span>{rows.length} sources shown</span></div>
    {!rows.length ? <EmptyState title="No sources match" copy="Clear the search or add a source if your role permits it." /> : <div className="source-table"><div className="source-table-head"><span>Source</span><span>Coverage</span><span>Mode</span><span>Timezone</span><span>Deep scan</span><span>Enabled</span><span /></div>{rows.map((source) => <div className="source-row" key={source.id}><div className="source-identity"><SourceBadge code={source.code} name={source.name} /><span><strong>{source.name}</strong><small>{source.url}</small></span></div><div><strong>{source.category}</strong><small>{source.region}</small></div><div>{source.rssUrl ? "RSS" : "Homepage"}</div><div>{source.timezone ?? "—"}</div><span>{source.deepScan ? "Yes" : "No"}</span><span>{source.enabled ? "Yes" : "No"}</span><div className="source-row-actions">{!readOnly && <button className="icon-button" onClick={() => onEdit(source)} aria-label={`Edit ${source.name}`}><Icon>✎</Icon></button>}</div></div>)}</div>}
  </div>;
}

export function AnalyticsView({ viewer, telemetry, feedback }: { viewer: ViewerProfile; telemetry: DetailedAnalytics | null; feedback: VocResponse[] }) {
  const [tab, setTab] = useState<"people" | "activity" | "voc">("people");
  const [selectedActor, setSelectedActor] = useState<string | null>(telemetry?.users[0]?.actor_id ?? null);
  const user = telemetry?.users.find((item) => item.actor_id === selectedActor) ?? telemetry?.users[0];
  const sessions = telemetry?.sessions.filter((item) => item.actor_id === user?.actor_id) ?? [];
  return <div className="page-content analytics-page admin-analytics"><PageIntro eyebrow="Restricted workspace telemetry" title="People & Product Analytics" copy={`Privacy-aware backend telemetry. Signed in as ${viewer.displayName}.`} />
    <div className="analytics-access-banner"><span><Icon>⌾</Icon></span><div><strong>Restricted backend surface</strong><p>Raw IPs and arbitrary event properties are excluded from this projection.</p></div><StatusBadge tone="approved">Restricted</StatusBadge></div>
    {!telemetry ? <EmptyState title="Analytics unavailable" copy="The backend did not return an analytics projection." /> : <><nav className="analytics-tabs">{[["people", "People & time"], ["activity", "Activity"], ["voc", "VOC"]].map(([id, label]) => <button key={id} className={tab === id ? "active" : ""} onClick={() => setTab(id as typeof tab)}>{label}{id === "voc" && <span>{feedback.length}</span>}</button>)}</nav>
      {tab === "people" && <><div className="engagement-kpis"><article><span>Known users</span><strong>{telemetry.summary.unique_actors}</strong><small>{telemetry.window_days}-day window</small></article><article><span>Total focus time</span><strong>{telemetry.summary.active_minutes}<em> min</em></strong><small>Visible-tab heartbeats; idle gaps capped at {telemetry.idle_cap_minutes} min</small></article><article><span>Sessions</span><strong>{telemetry.summary.session_count}</strong><small>{telemetry.summary.event_count} events</small></article><article><span>Stories reviewed</span><strong>{telemetry.summary.article_count}</strong><small>Distinct article IDs</small></article></div><div className="usage-workbench"><section className="user-usage-panel"><div className="usage-table-head"><span>User</span><span>Focus time</span><span>Sessions</span><span>Stories</span><span>Last seen</span></div><div className="usage-user-list">{telemetry.users.map((item) => <button className={user?.actor_id === item.actor_id ? "active" : ""} key={item.actor_id ?? "anonymous"} onClick={() => setSelectedActor(item.actor_id)}><span className="usage-avatar">{(item.actor_id ?? "A").slice(0, 2).toUpperCase()}</span><span><strong>{item.actor_id ?? "Unattributed"}</strong><small>Backend identity</small></span><strong>{item.active_minutes} min</strong><span>{item.session_count}</span><span>{item.article_count}</span><small>{item.last_seen_at ? new Date(item.last_seen_at).toLocaleString() : "—"}</small></button>)}</div></section><aside className="user-drilldown"><header><div><span className="eyebrow">User drilldown</span><h3>{user?.actor_id ?? "Unattributed"}</h3></div></header><div className="user-facts"><div><span>Time</span><strong>{user?.active_minutes ?? 0} min</strong></div><div><span>Events</span><strong>{user?.event_count ?? 0}</strong></div><div><span>Stories</span><strong>{user?.article_count ?? 0}</strong></div></div><div className="session-selector"><span>Most visited screens</span>{(user?.paths ?? []).slice(0, 5).map((path) => <div key={path.path}><span><strong>{path.path}</strong><small>{path.count} view{path.count === 1 ? "" : "s"}</small></span></div>)}<span>Sessions</span>{sessions.map((session) => <div key={session.session_id}><span><strong>{session.session_id.slice(0, 8)}</strong><small>{session.active_minutes} min · {session.event_count} events</small></span></div>)}</div></aside></div></>}
      {tab === "activity" && <div className="usage-workbench"><section className="activity-stream-panel"><div className="panel-title"><div><span className="eyebrow">Aggregated events</span><h3>Event types</h3></div></div>{Object.entries(telemetry.summary.event_types).sort((a, b) => b[1] - a[1]).map(([name, count]) => <article key={name}><div><strong>{name.replaceAll("_", " ")}</strong><p>{count} events in this window</p></div></article>)}</section><section className="activity-stream-panel"><div className="panel-title"><div><span className="eyebrow">Editorial behavior</span><h3>Article actions</h3></div></div>{Object.entries(telemetry.summary.action_types).sort((a, b) => b[1] - a[1]).map(([name, count]) => <article key={name}><div><strong>{name.replaceAll("_", " ")}</strong><p>{count} recorded action{count === 1 ? "" : "s"}</p></div></article>)}{!Object.keys(telemetry.summary.action_types).length && <p>No article actions were recorded in this window.</p>}</section><aside className="user-drilldown"><header><div><span className="eyebrow">Navigation</span><h3>Top screens</h3></div></header><div className="session-selector">{telemetry.summary.paths.slice(0, 10).map((path) => <div key={path.path}><span><strong>{path.path}</strong><small>{path.count} view{path.count === 1 ? "" : "s"}</small></span></div>)}</div><div className="user-facts"><div><span>Attributed</span><strong>{telemetry.coverage.actor_attribution_percent ?? 0}%</strong></div><div><span>Heartbeat</span><strong>{telemetry.coverage.heartbeat_events ?? 0}</strong></div></div></aside></div>}
      {tab === "voc" && <section className="voc-inbox"><div className="panel-title"><div><span className="eyebrow">Feedback inbox</span><h3>{feedback.length} submissions</h3></div></div>{feedback.map((item) => <article key={item.id}><header><div><strong>{item.actor_id ?? "Unattributed"}</strong><small>{item.page ?? "Context omitted"}</small></div><StatusBadge tone="live">{item.reference}</StatusBadge></header><blockquote>“{item.message}”</blockquote><footer><span>{item.rating}/5 usefulness</span><span>{item.category}</span></footer></article>)}{!feedback.length && <EmptyState title="No feedback yet" copy="VOC submissions will appear here." />}</section>}</>}
  </div>;
}

export function SettingsView({ viewer, theme, onOpenProfile, onThemeChange }: { viewer: ViewerProfile; theme: ColorTheme; onOpenProfile: () => void; onThemeChange: (theme: ColorTheme) => void }) {
  const scrollTo = (id: string) => document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" });
  return <div className="page-content settings-page">
    <PageIntro eyebrow="Workspace preferences" title="Settings" copy="Theme and density are device preferences; identity changes are persisted by the backend." />
    <div className="settings-layout"><aside><button className="active" onClick={() => scrollTo("identity-settings")}>Identity</button><button onClick={() => scrollTo("appearance-settings")}>Appearance</button></aside><div className="settings-main">
      <section id="identity-settings" className="settings-section identity-settings-section"><div><span className="eyebrow">Personal identity</span><h3>How this desk knows you</h3></div><div className="settings-identity-card"><span className="mini-avatar">{viewer.displayName.split(/\s+/).map((part) => part[0]).slice(0, 2).join("").toUpperCase()}</span><div><strong>{viewer.displayName}</strong><span>{viewer.contactEmail || viewer.accountEmail || "No contact email added"}</span></div><button className="secondary-button" onClick={onOpenProfile}>Edit personal details</button></div></section>
      <section id="appearance-settings" className="settings-section"><div><span className="eyebrow">Appearance</span><h3>Desk experience</h3></div><div className="setting-row"><div><strong>Theme</strong><span>Stored on this device for each profile.</span></div><div className="choice-group">{(["light", "dark"] as ColorTheme[]).map((item) => <button className={theme === item ? "active" : ""} key={item} onClick={() => onThemeChange(item)}>{item[0].toUpperCase() + item.slice(1)}</button>)}</div></div></section>
      <section className="settings-section"><div><span className="eyebrow">Web-wide research</span><h3>Not connected</h3><p>No ad-hoc search endpoint is available, so this version does not accept search credentials or display external results.</p></div></section>
    </div></div>
  </div>;
}
