"""Venture Lens topic definitions and resilient starter snapshots."""

GITHUB_CATEGORIES = [
    {
        "id": "ai-agents",
        "label": "AI agents",
        "description": "Autonomous workflows, tool use, and multi-agent systems.",
        "query": "ai agent in:name,description stars:>100",
        "accent": "violet",
    },
    {
        "id": "rag",
        "label": "RAG & retrieval",
        "description": "Retrieval, vector search, knowledge graphs, and grounding.",
        "query": "retrieval augmented generation in:name,description stars:>100",
        "accent": "cyan",
    },
    {
        "id": "machine-learning",
        "label": "Machine learning",
        "description": "Fast-moving ML frameworks, tooling, and applied research.",
        "query": "machine learning in:name,description stars:>300",
        "accent": "blue",
    },
    {
        "id": "deep-learning",
        "label": "Deep learning",
        "description": "Neural architectures, training systems, and model tooling.",
        "query": "deep learning in:name,description stars:>300",
        "accent": "rose",
    },
    {
        "id": "llm-efficiency",
        "label": "LLM efficiency",
        "description": "Inference, quantization, serving, and token-efficient systems.",
        "query": "llm inference in:name,description stars:>25",
        "accent": "amber",
    },
    {
        "id": "computer-vision",
        "label": "Computer vision",
        "description": "Multimodal perception, detection, generation, and vision models.",
        "query": "topic:computer-vision stars:>100",
        "accent": "emerald",
    },
    {
        "id": "ai-coding",
        "label": "AI coding & prompting",
        "description": "Coding agents, prompt libraries, rules files, and accessible software-building guidance.",
        "query": "AI coding prompts agent in:name,description,readme stars:>50",
        "accent": "lime",
    },
]

RESEARCH_CATEGORIES = [
    {
        "id": "agents",
        "label": "Agents",
        "description": "Reasoning, tool use, planning, and autonomous systems.",
        "query": 'all:"AI agent" OR all:"language model agent"',
        "accent": "violet",
    },
    {
        "id": "retrieval",
        "label": "Retrieval",
        "description": "RAG, search, grounding, and long-context knowledge access.",
        "query": 'all:"retrieval augmented generation"',
        "accent": "cyan",
    },
    {
        "id": "language-models",
        "label": "Language models",
        "description": "Training, alignment, evaluation, and inference.",
        "query": 'cat:cs.CL AND all:"language model"',
        "accent": "blue",
    },
    {
        "id": "multimodal",
        "label": "Multimodal",
        "description": "Vision-language, audio, video, and embodied intelligence.",
        "query": 'all:"multimodal model"',
        "accent": "rose",
    },
    {
        "id": "efficiency",
        "label": "Efficient AI",
        "description": "Compression, distillation, quantization, and serving.",
        "query": 'all:"model efficiency" OR all:"model compression"',
        "accent": "amber",
    },
    {
        "id": "software-engineering",
        "label": "AI software engineering",
        "description": "Code generation, software agents, testing, repair, and developer assistance.",
        "query": 'all:"code generation" OR all:"software engineering agent"',
        "accent": "lime",
    },
]


STARTER_REPOSITORIES = [
    {
        "id": "langchain-ai/langchain",
        "name": "langchain",
        "full_name": "langchain-ai/langchain",
        "description": "A framework for building context-aware reasoning applications.",
        "url": "https://github.com/langchain-ai/langchain",
        "owner": "langchain-ai",
        "language": "Python",
        "stars": 0,
        "forks": 0,
        "open_issues": 0,
        "topics": ["agents", "rag", "llm"],
        "category": "ai-agents",
        "updated_at": "",
        "starter_snapshot": True,
    },
    {
        "id": "huggingface/transformers",
        "name": "transformers",
        "full_name": "huggingface/transformers",
        "description": "Model definitions and tooling for state-of-the-art machine learning.",
        "url": "https://github.com/huggingface/transformers",
        "owner": "huggingface",
        "language": "Python",
        "stars": 0,
        "forks": 0,
        "open_issues": 0,
        "topics": ["transformers", "deep-learning", "nlp"],
        "category": "deep-learning",
        "updated_at": "",
        "starter_snapshot": True,
    },
    {
        "id": "vllm-project/vllm",
        "name": "vllm",
        "full_name": "vllm-project/vllm",
        "description": "A high-throughput and memory-efficient inference engine for LLMs.",
        "url": "https://github.com/vllm-project/vllm",
        "owner": "vllm-project",
        "language": "Python",
        "stars": 0,
        "forks": 0,
        "open_issues": 0,
        "topics": ["inference", "serving", "llm"],
        "category": "llm-efficiency",
        "updated_at": "",
        "starter_snapshot": True,
    },
    {
        "id": "run-llama/llama_index",
        "name": "llama_index",
        "full_name": "run-llama/llama_index",
        "description": "A data framework for context-augmented and retrieval-driven applications.",
        "url": "https://github.com/run-llama/llama_index",
        "owner": "run-llama",
        "language": "Python",
        "stars": 0,
        "forks": 0,
        "open_issues": 0,
        "topics": ["rag", "retrieval", "llm"],
        "category": "rag",
        "updated_at": "",
        "starter_snapshot": True,
    },
    {
        "id": "scikit-learn/scikit-learn",
        "name": "scikit-learn",
        "full_name": "scikit-learn/scikit-learn",
        "description": "Machine learning in Python with a broad collection of production-ready algorithms.",
        "url": "https://github.com/scikit-learn/scikit-learn",
        "owner": "scikit-learn",
        "language": "Python",
        "stars": 0,
        "forks": 0,
        "open_issues": 0,
        "topics": ["machine-learning", "python", "data-science"],
        "category": "machine-learning",
        "updated_at": "",
        "starter_snapshot": True,
    },
    {
        "id": "ultralytics/ultralytics",
        "name": "ultralytics",
        "full_name": "ultralytics/ultralytics",
        "description": "Computer-vision models and tooling for detection, tracking, and deployment.",
        "url": "https://github.com/ultralytics/ultralytics",
        "owner": "ultralytics",
        "language": "Python",
        "stars": 0,
        "forks": 0,
        "open_issues": 0,
        "topics": ["computer-vision", "object-detection", "deep-learning"],
        "category": "computer-vision",
        "updated_at": "",
        "starter_snapshot": True,
    },
    {
        "id": "natnew/Awesome-Prompt-Engineering",
        "name": "Awesome-Prompt-Engineering",
        "full_name": "natnew/Awesome-Prompt-Engineering",
        "description": "Prompt and context engineering resources, including coding, agents, evaluation, and production practices.",
        "url": "https://github.com/natnew/Awesome-Prompt-Engineering",
        "owner": "natnew",
        "language": "Markdown",
        "stars": None,
        "forks": None,
        "open_issues": None,
        "topics": ["prompt-engineering", "ai-coding", "context-engineering"],
        "category": "ai-coding",
        "updated_at": "",
        "starter_snapshot": True,
    },
]

STARTER_PAPERS = [
    {
        "id": "1706.03762",
        "title": "Attention Is All You Need",
        "summary": "Introduces the Transformer architecture, replacing recurrence with attention.",
        "url": "https://arxiv.org/abs/1706.03762",
        "pdf_url": "https://arxiv.org/pdf/1706.03762",
        "authors": ["Ashish Vaswani", "Noam Shazeer", "Niki Parmar"],
        "published_at": "2017-06-12",
        "updated_at": "2017-06-12",
        "category": "language-models",
        "starter_snapshot": True,
    },
    {
        "id": "2005.11401",
        "title": "Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks",
        "summary": "Combines parametric generation with retrieved non-parametric memory.",
        "url": "https://arxiv.org/abs/2005.11401",
        "pdf_url": "https://arxiv.org/pdf/2005.11401",
        "authors": ["Patrick Lewis", "Ethan Perez", "Aleksandra Piktus"],
        "published_at": "2020-05-22",
        "updated_at": "2021-04-12",
        "category": "retrieval",
        "starter_snapshot": True,
    },
]
